server:
  port: 8080

#spring
spring:
  encoding:
    charset: "UTF-8"
  application:
    name: "ps-cidades-estados-ibge"
    version: "1.0.0"
    description: "Api de listagem de cidades atualizadas"


application:
  clients:
    ibge:
      estados-cidades:
        baseUrl: "https://servicodados.ibge.gov.br/"